# Generated by Django 4.1.6 on 2024-03-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.PositiveIntegerField(max_length=100)),
                ('Task_Title', models.CharField(max_length=100)),
                ('Task_Domain', models.CharField(max_length=100)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
    ]
