# Generated by Django 4.1.6 on 2024-03-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Start_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
